cloudhousetech/content

code/ruby/policies-delete.rb
currently being used to keep the versatile demo account clean
=> script to delete policies from an account (clean up)

code/python/change-nodes-environment.py
Fixed Content-Type headers, provide lines for HTTPSConnection and unverified contexts
=> Provide code for HTTPS connections in changing node environments

code/powershell/azure_resource_node.ps1, code/python/node-membership-via-csv.py
- Pulls node information from a CSV file based on a set of filters, and adds/removes those nodes to/from the targetted node group
=> Added dynamic node group membership script

code/powershell/query_vuln_endpoint.ps1
Should work with self-signed cert appliance; please review and let me know if this works in the intended manner
=> CS-349 Script to query vulnerabilities endpoint

failover/app/bin/pg-failover-sync.sh, failover/app/fleet/postgres-failover-sync.service, failover/app/fleet/postgres-failover-sync.timer, failover/etc/environment_failover
Assumes that master has fix from APPK-43
=> CS-434 Script and service files for db sync between master, backup appliances

code/powershell/get-last-login-events.ps1
- One CI per user, attributes as chronological logon events
=> Added script for getting last logins on windows as a scan option

code/powershell/set-hostname-to-display-name.ps1
Required parameters for api keys and url, with an optional parameter for
`dry_run` to see what would be changed
=> Add set-hostname-to-display-name powershell script

puppet/upguard.rb, puppet/upguard.yaml
https://guardrail.zendesk.com/agent/tickets/55493
=> v1.2.0 - Use SSH and WinRM creds from config

puppet/upguard.rb
Can now do something like:
`cat /var/log/puppetlabs/puppetserver/puppetserver.log | grep "upguard puppet.upguard.org"`
- Tidied up node create post, fixed password escaping
- Standardized log prefixing
=> v1.2.3 - Fix issues with password escaping, easily grep-able logs

code/powershell/custom_reporting_with_api.ps1
Example of custom reporting using the API
=> Added Powershell script for customer reporting

puppet/upguard.rb
Need to add: `:sleep_before_scan: 120` to upguard.yaml.
=> v1.4.3 - sleep after node creation to let resolve.conf populate

code/powershell/custom-node-script-example-oracle.ps1
Sample powershell for pulling data out of Oracle SQL queries and formatting it the way we expect for a script path custom node.
Includes comments explaining the JSON structure that we expect.
=> Custom node example powershell

ansible/README.md, ansible/upguard_node/library/upguard_node.py, ansible/upguard_node/play.yml, ansible/upguard_node/requirements.txt
Created base ansible readme framework.
Added 'upguard_node' ansible module.
Added 'play.yml' as a working example.
=> adding upguard_node ansible module

code/archive/powershell/change_report.ps1
Script grouped a node's CIs of only the same type together
Now groups the individual CIs
=> Finds Specific CIs that change

code/api/ruby/list_nodes.rb
Calls the list node API endpoint
-enforces TLS1.2
-paginates
-has a status and last scan status flag
=> Ruby list nodes

policies/PCI_3_2_Server_Hardening_Windows.json
"20170913-0". If you update this file, please update this element as well.
Someday this will be automated but its time to get started using an actual repo
and will have to add versioning feature on the fly.
=> PCI Server Hardening Policy - Windows

code/python/snippets/api-call.py, code/python/snippets/arguments.py
This PR adds simple snippets for gettings up and running with a python script to call the API.
As it stands now, you'd basically copy the contents of both snippets to your script to get started.
There is a description of each snippet at the top of the corresponding file. The description also includes how to use the snippet.
This will help me when building a script for a customer, so I feel it can be used by others to make python scripts efficiently.
=> Python snippets

code/powershell/scan-options-share-permissions.ps1
I originally found this online, but tested it locally and with a customer and it works as expected.
=> Add scan option to monitor file share permissions

policies/PCI_3_2_Audit_Check_Windows.json
Removed 3 policies that were not backwards compatible with older versions of windows.
Some cleanup of regular expressions found during QA effort.
Not sure where the lines 460-485 came from??
=> Qa performed by upwork

code/powershell/get-used-space.ps1
- Produces CIs for used space on each disk attached to the node
- The key is 'Drive'
=> Added freespace powershell scan option

code/powershell/start_scan_if_connected_and_required.ps1
- This script will query to see if the node it is on has connectivity to an STA/appliance
- It will check if a given time has elapsed since the last successful scan for that node
- If both conditions are met, it will kick off a scan job for that node
=> Connect and scan script

action templates/email/failures.liquid
@alansp this has the new structure but could still probably do with some styling and conditions around expect results and conditionals.
=> Changed policy result structure

scan options/windows/powershell/share-permissions.ps1, scan options/windows/powershell/stored-procedures.ps1
This PR moves the scan options to their own directory, and adds a scan option for stored procedures for MS SQL servers
=> Organize Powershell scan options

code/python/start_scan_if_connected_and_required.py
=> Add python version of start_scan_if_connected_and_required

action templates/email/diffs_details.liquid
Small liquidsyntax to compare old and new attribute values in diffs.
=> Diffs detail liquid script

code/powershell/Add-GithubRepoNodes.ps1
Script to take all GitHub repositories and add them as Guardian instance nodes.
=> Adds Add-GitHubRepoNodes script

policies/aws_cis_iam_policy.json
Diff isn't too bad. We need to strip out all the UI stuff from the policy export though.
=> IAM policy updates

policies/aws_cis_iam_policy.json
This PR is dependent on GLA-627 - Update
=> Update IAM policy to include PolicyVersion CI check

code/powershell/Get-JiraCloudNode.ps1, code/powershell/Get-LastPassNode.ps1, code/powershell/Get-PingdomNode.ps1
Adds PowerShell scripts to pull obvious data back from 3 cloud services:
- Jira
- LastPass
- Pingdom
=> Jira lastpass pingdom

policies/aws_cis_access_analyzer_policy.json, policies/aws_cis_cloudtrail_policy.json, policies/aws_cis_config_service_policy.json, policies/aws_cis_ebs_policy.json, policies/aws_cis_iam_policy.json, policies/aws_cis_kms_policy.json, policies/aws_cis_rds_policy.json, policies/aws_cis_s3_policy.json
Not sure if it's big deal, but just keeping things tidy.
=> Remove "selectList" keys from json policies

api/powershell/start-scan-if-connected-and-required.ps1
Customer wants to start scanning laptops, which have intermittent connectivity. Updated the script for checking scan status on Windows logon to work with Guardian-branded agents.
=> Update agent startup script
